CREATE SCHEMA IF NOT EXISTS payments;

CREATE TABLE IF NOT EXISTS payments.payment_proofs (
  id BIGSERIAL PRIMARY KEY,
  display_id VARCHAR(64) NOT NULL UNIQUE,
  proof_text TEXT,
  mime_type VARCHAR(128),
  file_base64 TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

